SearchInput 功能
orangeCatGang/JiaBaMap pull request #8
Opened 2024-12-10 08:26 UTC by tizza14

1. 使用pinia 管理 navigateToSearch 的狀態 -> keywordStore.js
2. 放入 keywordStore.js 並引入storeType.vue 跟個人頁的 RatingCard.vue ，點擊關鍵字按鈕跳轉至搜尋頁並渲染 input 與 URL
3. SearchInput 加入 debounce (防抖)
4. searchInput RWD

2024-12-10 10:18 UTC, jamesxiao01 commented on src/components/MapComponent.vue
> -            });
應該選106-109行

2024-12-10 10:43 UTC, jamesxiao01 requested changes
這邊修改一下即可
![1733825566417](https://github.com/user-attachments/assets/675ac180-6836-4814-8d39-e9631bc6f6e0)

2024-12-10 18:56 UTC, yoyo708 commented on src/components/Header.vue
> +
要保留原本128的icon~

2024-12-11 02:22 UTC, juliewah approved these changes

2024-12-11 02:23 UTC, yoyo708 approved these changes

2024-12-11 02:55 UTC, jamesxiao01 approved these changes
ok囉

2024-12-12 01:57 UTC, wanruliao approved these changes

2024-12-12 02:10 UTC, han7795 approved these changes

2024-12-12 02:54 UTC, stu261426 approved these changes

2024-12-12 04:20 UTC, merged